// filters
export const TOGGLE_FILTERS = 'TOGGLE_FILTERS';
export const OPEN_FILTERS = 'OPEN_FILTERS';
export const CLOSE_FILTERS = 'CLOSE_FILTERS';
export const UPDATE_LANGUAGE_FILTER = 'UPDATE_LANGUAGE_FILTER';
export const UPDATE_LAST_COMMIT_FILTER = 'UPDATE_LAST_COMMIT_FILTER';
export const UPDATE_REPO_CREATED_FILTER = 'UPDATE_REPO_CREATED_FILTER';
export const UPDATE_STARS_FILTER = 'UPDATE_STARS_FILTER';
export const UPDATE_FORKS_FILTER = 'UPDATE_FORKS_FILTER';
export const UPDATE_AUTHOR_FILTER = 'UPDATE_AUTHOR_FILTER';
export const SET_AUTHOR_FILTER_TYPING_TIMEOUT = 'SET_AUTHOR_FILTER_TYPING_TIMEOUT';
export const UPDATE_SHOW_FORKED_REPOS_FILTER = 'UPDATE_SHOW_FORKED_REPOS_FILTER';

// search
export const TYPING_IN_SEARCH_FIELD = 'TYPING_IN_SEARCH_FIELD';
export const UPDATE_SEARCH_FIELD = 'UPDATE_SEARCH_FIELD';
export const UPDATE_SEARCH_RESULTS = 'UPDATE_SEARCH_RESULTS';
export const GITHUB_SEARCH_REQUEST = 'GITHUB_SEARCH_REQUEST';
export const GITHUB_SEARCH_SUCCESS = 'GITHUB_SEARCH_SUCCESS';
export const GITHUB_SEARCH_FAILURE  = 'GITHUB_SEARCH_FAILURE';
export const SET_SEARCH_FIELD_TYPING_TIMEOUT = 'SET_SEARCH_FIELD_TYPING_TIMEOUT';
export const CLEAR_SEARCH_RESULTS = 'CLEAR_SEARCH_RESULTS';
export const UPDATE_SEARCH_RESULTS_COUNT_TOTAL = 'UPDATE_SEARCH_RESULTS_COUNT_TOTAL';
export const DOM_LOADED = 'DOM_LOADED';

// sorting
export const CHANGE_SORT_TYPE = 'CHANGE_SORT_TYPE';
export const CHANGE_SORT_ORDER = 'CHANGE_SORT_ORDER';
